// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// CONFIGURACIÓN DEL NUEVO SERVIDOR - Usar variables de entorno
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

console.log('🔧 CLIENTE SUPABASE - NUEVO SERVIDOR');
console.log('🔗 URL:', SUPABASE_URL);
console.log('🔑 Key:', SUPABASE_PUBLISHABLE_KEY ? 'PRESENTE' : 'AUSENTE');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);